"""empty message

Revision ID: 058f3a1d6208
Revises: None
Create Date: 2016-06-02 15:49:36.647110

"""

# revision identifiers, used by Alembic.
revision = '058f3a1d6208'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('zipcode', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('validation_failure', postgresql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(u'NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=False)
    op.create_index(op.f('ix_orders_name'), 'orders', ['name'], unique=False)
    op.create_index('ix_orders_state_zipcode', 'orders', ['state', 'zipcode'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_state_zipcode', table_name='orders')
    op.drop_index(op.f('ix_orders_name'), table_name='orders')
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.drop_table('orders')
    ### end Alembic commands ###
