"""empty message

Revision ID: 628d87aeed63
Revises: 54f638c74711
Create Date: 2016-05-16 14:07:24.064007

"""

# revision identifiers, used by Alembic.
revision = '628d87aeed63'
down_revision = '54f638c74711'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_order_email'), 'order', ['email'], unique=False)
    op.create_index(op.f('ix_order_name'), 'order', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_name'), table_name='order')
    op.drop_index(op.f('ix_order_email'), table_name='order')
    ### end Alembic commands ###
