"""empty message

Revision ID: 8c66fa00f8f9
Revises: 628d87aeed63
Create Date: 2016-05-16 14:27:29.520536

"""

# revision identifiers, used by Alembic.
revision = '8c66fa00f8f9'
down_revision = '628d87aeed63'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_state_zipcode', 'order', ['state', 'zipcode'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_state_zipcode', table_name='order')
    ### end Alembic commands ###
