"""empty message

Revision ID: 9c9404d755e6
Revises: 8c66fa00f8f9
Create Date: 2016-05-25 22:49:29.816545

"""

# revision identifiers, used by Alembic.
revision = '9c9404d755e6'
down_revision = '8c66fa00f8f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=True)
    op.alter_column('order', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('order', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('order', 'zipcode',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'zipcode',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('order', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('order', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('order', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
    op.alter_column('order', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    ### end Alembic commands ###
