"""empty message

Revision ID: fd13360940d6
Revises: None
Create Date: 2016-05-15 15:49:43.002098

"""

# revision identifiers, used by Alembic.
revision = 'fd13360940d6'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('validation_failure', postgresql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()')),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), onupdate=datetime.now),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    ### end Alembic commands ###
